import { Doctor, Appointment, Prescription } from './types';

export const INITIAL_DOCTORS: Doctor[] = [
  {
    id: 'doc-1',
    name: 'Dr. Rajesh Sharma',
    email: 'dr.rajesh@medisync.care',
    specialty: 'Cardiology',
    experienceYears: 14,
    qualifications: 'MBBS, MD (Medicine), DM (Cardiology), FACC',
    hospital: 'Apollo Heart Institute',
    location: 'New Delhi, Connaught Place',
    consultationFee: 1200,
    rating: 4.9,
    reviewsCount: 142,
    avatar: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=400&auto=format&fit=crop&q=80',
    about: 'Senior Interventional Cardiologist specializing in preventive heart health, coronary angiographies, and hypertension management with over 14 years of clinical experience.',
    availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
    timeSlots: ['09:00 AM', '10:30 AM', '11:45 AM', '02:00 PM', '04:30 PM', '06:00 PM'],
    isAvailableToday: true,
  },
  {
    id: 'doc-2',
    name: 'Dr. Priya Nair',
    email: 'dr.priya@medisync.care',
    specialty: 'Dermatology',
    experienceYears: 9,
    qualifications: 'MBBS, MD (Dermatology, Venereology & Leprosy)',
    hospital: 'SkinCare & Laser Center',
    location: 'Bangalore, Indiranagar',
    consultationFee: 800,
    rating: 4.8,
    reviewsCount: 198,
    avatar: 'https://images.unsplash.com/photo-1594824813583-7c5780516c95?w=400&auto=format&fit=crop&q=80',
    about: 'Expert in aesthetic dermatology, acne scarring treatments, hair-fall therapy, and advanced laser skin rejuvenation.',
    availableDays: ['Monday', 'Wednesday', 'Friday', 'Saturday'],
    timeSlots: ['10:00 AM', '11:15 AM', '01:00 PM', '03:30 PM', '05:15 PM'],
    isAvailableToday: true,
  },
  {
    id: 'doc-3',
    name: 'Dr. Amitav Mukherjee',
    email: 'dr.amitav@medisync.care',
    specialty: 'Orthopedics',
    experienceYears: 16,
    qualifications: 'MBBS, MS (Orthopedics), M.Ch (Joint Replacement)',
    hospital: 'Fortis Bone & Joint Hospital',
    location: 'Mumbai, Bandra West',
    consultationFee: 1100,
    rating: 4.9,
    reviewsCount: 176,
    avatar: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=400&auto=format&fit=crop&q=80',
    about: 'Renowned orthopedic surgeon specializing in robotic knee and hip replacements, sports injury rehabilitation, and arthroscopic procedures.',
    availableDays: ['Tuesday', 'Thursday', 'Saturday'],
    timeSlots: ['09:30 AM', '11:00 AM', '02:30 PM', '04:00 PM'],
    isAvailableToday: true,
  },
  {
    id: 'doc-4',
    name: 'Dr. Sneha Verma',
    email: 'dr.sneha@medisync.care',
    specialty: 'Pediatrics',
    experienceYears: 11,
    qualifications: 'MBBS, DCH, DNB (Pediatrics)',
    hospital: 'Rainbow Children Hospital',
    location: 'Hyderabad, Banjara Hills',
    consultationFee: 700,
    rating: 4.9,
    reviewsCount: 230,
    avatar: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=400&auto=format&fit=crop&q=80',
    about: 'Compassionate pediatrician devoted to child developmental milestones, immunization schedules, newborn care, and pediatric infections.',
    availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'],
    timeSlots: ['09:00 AM', '10:00 AM', '11:30 AM', '03:00 PM', '05:00 PM'],
    isAvailableToday: true,
  },
  {
    id: 'doc-5',
    name: 'Dr. Vikram Sethi',
    email: 'dr.vikram@medisync.care',
    specialty: 'Neurology',
    experienceYears: 18,
    qualifications: 'MBBS, MD, DM (Neurology)',
    hospital: 'Apex Neuro Sciences Center',
    location: 'Gurugram, Sector 44',
    consultationFee: 1500,
    rating: 4.8,
    reviewsCount: 115,
    avatar: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=400&auto=format&fit=crop&q=80',
    about: 'Distinguished neurologist with extensive expertise in stroke management, epilepsy, migraines, Parkinson disease, and neuro-electrophysiology.',
    availableDays: ['Monday', 'Wednesday', 'Thursday'],
    timeSlots: ['10:00 AM', '12:00 PM', '03:00 PM', '05:30 PM'],
    isAvailableToday: false,
  },
  {
    id: 'doc-6',
    name: 'Dr. Ananya Roy',
    email: 'dr.ananya@medisync.care',
    specialty: 'General Medicine',
    experienceYears: 8,
    qualifications: 'MBBS, MD (General Medicine)',
    hospital: 'CarePlus Multispecialty Clinic',
    location: 'Kolkata, Salt Lake',
    consultationFee: 600,
    rating: 4.7,
    reviewsCount: 165,
    avatar: 'https://images.unsplash.com/photo-1651008376811-b90baee60c1f?w=400&auto=format&fit=crop&q=80',
    about: 'Holistic internal medicine consultant focused on lifestyle disorders, diabetes management, infectious diseases, and preventive adult health checks.',
    availableDays: ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'],
    timeSlots: ['08:30 AM', '10:00 AM', '11:30 AM', '04:00 PM', '06:00 PM'],
    isAvailableToday: true,
  }
];

export const INITIAL_APPOINTMENTS: Appointment[] = [
  {
    id: 'appt-101',
    doctorId: 'doc-1',
    doctorName: 'Dr. Rajesh Sharma',
    doctorSpecialty: 'Cardiology',
    doctorAvatar: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=400&auto=format&fit=crop&q=80',
    patientId: 'pat-1',
    patientName: 'Rohan Gupta',
    patientEmail: 'rohan.gupta@example.com',
    patientPhone: '+91 98765 43210',
    patientAge: 42,
    patientGender: 'Male',
    appointmentDate: new Date(Date.now() + 86400000).toISOString().split('T')[0], // Tomorrow
    appointmentTime: '10:30 AM',
    consultationType: 'in-clinic',
    symptoms: 'Occasional chest tightness after brisk walking and mild breathlessness.',
    status: 'confirmed',
    fee: 1200,
    createdAt: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: 'appt-102',
    doctorId: 'doc-1',
    doctorName: 'Dr. Rajesh Sharma',
    doctorSpecialty: 'Cardiology',
    doctorAvatar: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=400&auto=format&fit=crop&q=80',
    patientId: 'pat-2',
    patientName: 'Sunita Mehra',
    patientEmail: 'sunita.mehra@example.com',
    patientPhone: '+91 98111 22334',
    patientAge: 58,
    patientGender: 'Female',
    appointmentDate: new Date().toISOString().split('T')[0], // Today
    appointmentTime: '02:00 PM',
    consultationType: 'video',
    symptoms: 'Follow-up for blood pressure medication review and lipid profile check.',
    status: 'pending',
    fee: 1200,
    createdAt: new Date(Date.now() - 7200000).toISOString(),
  },
  {
    id: 'appt-103',
    doctorId: 'doc-2',
    doctorName: 'Dr. Priya Nair',
    doctorSpecialty: 'Dermatology',
    doctorAvatar: 'https://images.unsplash.com/photo-1594824813583-7c5780516c95?w=400&auto=format&fit=crop&q=80',
    patientId: 'pat-1',
    patientName: 'Rohan Gupta',
    patientEmail: 'rohan.gupta@example.com',
    patientPhone: '+91 98765 43210',
    patientAge: 42,
    patientGender: 'Male',
    appointmentDate: new Date(Date.now() - 172800000).toISOString().split('T')[0], // 2 days ago
    appointmentTime: '11:15 AM',
    consultationType: 'in-clinic',
    symptoms: 'Persistent dry itchy skin patches on elbows and forearms.',
    status: 'completed',
    fee: 800,
    createdAt: new Date(Date.now() - 200000000).toISOString(),
    prescription: {
      id: 'presc-501',
      appointmentId: 'appt-103',
      doctorId: 'doc-2',
      doctorName: 'Dr. Priya Nair',
      doctorSpecialty: 'Dermatology',
      patientId: 'pat-1',
      patientName: 'Rohan Gupta',
      diagnosis: 'Mild Eczematous Dermatitis triggered by seasonal dryness.',
      items: [
        {
          medicine: 'Hydrocortisone Cream 1%',
          dosage: 'Apply thin layer',
          frequency: 'Twice daily',
          duration: '7 Days',
          instructions: 'Apply on affected areas only after lukewarm shower',
        },
        {
          medicine: 'Cetirizine 10mg',
          dosage: '1 Tablet',
          frequency: 'Once at bedtime',
          duration: '5 Days',
          instructions: 'After dinner to relieve nocturnal itching',
        },
        {
          medicine: 'Ceramide Moisture Barrier Lotion',
          dosage: 'Liberal amount',
          frequency: '3 times daily',
          duration: '30 Days',
          instructions: 'Keep skin well hydrated throughout the day',
        }
      ],
      advice: 'Avoid harsh chemical soaps. Drink 2.5L water daily. Revisit in 2 weeks if patches persist.',
      createdAt: new Date(Date.now() - 170000000).toISOString(),
    }
  }
];
